stages:
- build

Build the client:
  stage: build
  image: niklaskorz/makisu-alpine
  script:
    - echo "{\"$CI_REGISTRY\":{\".*\":{\"basic\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}}" > /registry-config.yaml
    - makisu build --push=$CI_REGISTRY --modifyfs=true -t=$CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHA --registry-config=/registry-config.yaml $CI_PROJECT_DIR/client

Build the server:
  stage: build
  image: niklaskorz/makisu-alpine
  script:
    - echo "{\"$CI_REGISTRY\":{\".*\":{\"basic\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}}" > /registry-config.yaml
    - makisu build --push=$CI_REGISTRY --modifyfs=true -t=$CI_REGISTRY_IMAGE/server:$CI_COMMIT_SHA --registry-config=/registry-config.yaml $CI_PROJECT_DIR/server
