stages:
- build

Build the client:
  stage: build
  image: niklaskorz/makisu-alpine
  script:
    - echo "{\"$CI_REGISTRY\":{\".*\":{\"basic\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}}" > /registry-config.yaml
    - cat /registry-config.yaml
    - makisu build --push=$CI_REGISTRY --modifyfs=true -t $CI_PROJECT_PATH/client:$CI_COMMIT_SHA --registry-config=/registry-config.yaml -f client/Dockerfile $CI_PROJECT_DIR

Build the server:
  stage: build
  image: niklaskorz/makisu-alpine
  script:
    - echo "{\"$CI_REGISTRY\":{\".*\":{\"basic\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}}" > /registry-config.yaml
    - makisu build --push=$CI_REGISTRY --modifyfs=true -t $CI_PROJECT_PATH/server:$CI_COMMIT_SHA --registry-config=/registry-config.yaml -f server/Dockerfile $CI_PROJECT_DIR
