version: "3"

networks:
  internal:
    external: false
  proxy:
    external: false

volumes:
  mongo:
  redis:

services:
  mongodb:
    image: "mongo:3.6"
    volumes:
      - 'mongo:/data/db'
    networks:
      - internal
  nats:
    image: "nats:1.1.0"
    networks:
      - internal
  redis:
    image: "redis:5"
    volumes:
      - 'redis:/data'
    networks:
      - internal
  server:
    build: server
    environment:
      - MONGODB_HOST=mongodb
      - NATS_HOST=nats
      - REDIS_HOST=redis
    labels:
      traefik.enable: "true"
      traefik.port: "3000"
      traefik.frontend.rule: "Path:/graphql,/graphiql,/subscriptions"
      traefik.docker.network: nkchat_proxy
    networks:
      - internal
      - proxy
    depends_on:
      - mongodb
      - nats
  client:
    build: client
    labels:
      traefik.enable: "true"
      traefik.port: "3000"
      traefik.frontend.rule: "PathPrefix:/"
      traefik.docker.network: nkchat_proxy
    networks:
      - internal
      - proxy
