version: "3"

networks:
  proxy:
    external: false

services:
  traefik:
    image: "traefik:1.6"
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
