version: "3"

services:
  mongodb:
    image: "mongo:3.6"
  nats:
    image: "nats:1.0.6"
  server:
    build: "git@gitlab.com:webengineering2/server.git"
    links:
      - "mongodb:mongodb"
      - "nats:nats"
    deploy:
      labels:
        traefik.backend: server
        traefik.port: "3000"
        traefik.frontend.rule: "Host:chat.niklaskorz.de;Path:/graphql,/graphiql,/subscriptions"
  client:
    build: "git@gitlab.com:webengineering2/client.git"
    deploy:
      labels:
        traefik.backend: client
        traefik.port: "3000"
        traefik.frontend.rule: "Host:chat.niklaskorz.de"
