version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  mongodb:
    image: "mongo:3.6"
    networks:
      - internal
  nats:
    image: "nats:1.0.6"
    networks:
      - internal
  server:
    build: server
    environment:
      - MONGODB_HOST=mongodb
      - NATS_HOST=nats
    labels:
      traefik.backend: server
      traefik.port: "3000"
      traefik.frontend.rule: "Host:chat.niklaskorz.de;Path:/graphql,/graphiql,/subscriptions"
      traefik.docker.network: proxy
    networks:
      - internal
      - proxy
    depends_on:
      - mongodb
      - nats
  client:
    build: client
    labels:
      traefik.backend: client
      traefik.port: "3000"
      traefik.frontend.rule: "Host:chat.niklaskorz.de"
      traefik.docker.network: proxy
    networks:
      - internal
      - proxy

