version: "3"

networks:
  proxy:
    external: true

services:
  server:
    labels:
      traefik.frontend.rule: "Host:chat.niklaskorz.de;Path:/graphql,/graphiql,/subscriptions"
  client:
    labels:
      traefik.frontend.rule: "Host:chat.niklaskorz.de"
