version: "3"

services:
  traefik:
    image: "traefik:1.6"
    command: "-c /dev/null --api --entrypoints='Name:http Address::9000' --docker --docker.exposedbydefault=false --docker.domain=docker.localhost"
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
