version: "3"

networks:
  internal:
    external: false

volumes:
  mongo:

services:
  mongodb:
    image: "mongo:3.6"
    volumes:
      - 'mongo:/data/db'
    networks:
      - internal
  nats:
    image: "nats:1.0.6"
    networks:
      - internal
  server:
    build: server
    environment:
      - MONGODB_HOST=mongodb
      - NATS_HOST=nats
    networks:
      - internal
    depends_on:
      - mongodb
      - nats
  client:
    build: client
    networks:
      - internal

